### ISSUE TITLE
Boolean

### ISSUE THREAD

**Issue by RoasgdChees** [453452hw/bhack#2]
In computer science, the Boolean data type is a data type that has one of two possible values (usually denoted true and false) which is intended to represent the two truth values of logic and Boolean algebra. It is named after George Boole, who first defined an algebraic system of logic in the mid 19th century. The Boolean data type is primarily associated with conditional statements, which allow different actions by changing control flow depending on whether a programmer-specified Boolean condition evaluates to true or false. It is a special case of a more general logical data type (see probabilistic logic)—logic doesn't always need to be Boolean.

**Comment by 453452hw** [comment]
thanks really needed this

**Comment by RoasgdChees** [comment]
> thanks really needed this

no problem, always there to help
